### ISSUE TITLE
ALTERNATIVE SNIPPET: stat with fixed width

### ISSUE THREAD

**Issue by Toxin95** [Togn3K/kickbot_py#16]
def stat(bot, update):
    chat_id = update.message.chat_id
    pos = 1
    message = Texttable()
    message.add_row(['position', 'username', 'kicked_times'])
    f = pandas.read_csv('res/' + str(chat_id) + '/users.csv', sep=';')
    sorted_f = pandas.DataFrame(f)
    sorted_f = sorted_f.sort_values(['kicked'], ascending=False)
    for user in sorted_f.values:
        message.add_row([pos, user[1].split('@')[1], user[2]])
        pos = pos + 1
    message = message.draw()
    bot.send_message(chat_id=chat_id, text='<code>' + message + '</code>', parse_mode=telegram.ParseMode.HTML)

**Comment by Togn3K** [comment]
library used : tabulate
